function OperacionesMatriz(A,B)
disp('Matrices traspuestas:')
disp(transpose(A))
disp(transpose(B))
disp('')
disp('Inversa de A:')
disp(inv(A))
disp('')
disp('Determinante y rango de A:')
disp(det(A))
disp(rank(A))
disp('')
disp('Producto matricial de ambas matrices:')
disp(A * B)
disp('')
disp('Producto de las primeras columnas de cada matriz ')
disp(A(:,1) .* B(:,1))
disp('')
disp('Concatenación de las primeras filas:')
disp([A(1,:), B(1,:)])
disp('')
disp('Concatenación de las primeras columnas:')
disp([A(:,1); B(:,1)])
end

